apiVersion: apps/v1
kind: Deployment
metadata:
  name: webclient
  labels:
    app: webclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webclient
  template:
    metadata:
      labels:
        app: webclient
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: webclient
        image: sbraer/grpcclient:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_NAME
          value: "http://webserver"
