apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
  - name: client
    image: sbraer/client
    imagePullPolicy: Never #IfNotPresent #Always
    env:
    - name: SERVER_NAME
      value: "https://webserver:5001"
