---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  annotations:
    #linkerd.io/inject: enabled
spec:
  selector:
    app: httpserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: webserver
        image: sbraer/httpservice
        imagePullPolicy: Never #IfNotPresent #Always
        env:
        - name: RANDOM_ERROR
          value: "true"
