---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    #nodePort: 30000
  #type: NodePort #LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: sbraer/server
        imagePullPolicy: Never #IfNotPresent #Always
        env:
        - name: REMOTE
          value: a
        - name: USE_CERTIFICATE
          value: "true"
