---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  annotations:
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: sbraer/grpcservice:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: USE_CERTIFICATE
          value: "true"
        - name: CERTIFICATE_PFX_FILE
          value: /usr/local/share/ca-certificates/domain.name.pfx
        - name: PORT
          value: "443"
        command:
        - bash
        - "-c"
        - |
          set ex
          chmod 644 /usr/local/share/ca-certificates/ca.crt
          update-ca-certificates
          dotnet AzGrpcService.dll
        volumeMounts:
        - name: certificates
          mountPath: /usr/local/share/ca-certificates
      volumes:
      - name: certificates
        secret:
          secretName: certificate-webserver
