---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: webserver
        image: sbraer/server
        imagePullPolicy: Never #IfNotPresent #Always
        env:
        - name: USE_CERTIFICATE
          value: "true"
        - name: CERTIFICATE_PFX_FILE
          value: /usr/local/share/ca-certificates/domain.name.pfx
        - name: RANDOM_ERROR
          value: "false"
        command:
        - bash
        - "-c"
        - |
          set ex
          chmod 644 /usr/local/share/ca-certificates/ca.crt
          update-ca-certificates
          dotnet AzGrpcService.dll
        volumeMounts:
        - name: certificates
          mountPath: /usr/local/share/ca-certificates
          #readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: certificate-webserver
